name: React Build CI
run-name: ${{ github.actor }} started build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1

      - name: install dependencies
        run: npm install

      - name: Check environment variables validation
        run: |
          echo $PWD >> build.txt; echo "mahesh" >> build.txt; echo "${{secrets.ACCESS_TOKEN }}" >> build.txt;

      - name: Create .env files
        run: echo "${{ env.DEV_ENV }}" >> .env;

      - name: build react js files
        run: npm run build --if-present

      - name: build complete
        run: echo "$USER"
